apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    azure-key-vault-env-injection: enabled

---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-tenant-id
  namespace: default
spec:
  vault:
    name: video-indexer-we-kv
    object:
      type: secret
      name: tenantId

---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-client-id
  namespace: default
spec:
  vault:
    name: video-indexer-we-kv
    object:
      type: secret
      name: clientId

---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-client-secret
  namespace: default
spec:
  vault:
    name: video-indexer-we-kv
    object:
      type: secret
      name: clientSecret

---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-video-indexer-api-key
  namespace: default
spec:
  vault:
    name: video-indexer-we-kv
    object:
      type: secret
      name: videoIndexerApiKey

---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-storage-account-name
  namespace: default
spec:
  vault:
    name: video-indexer-we-kv
    object:
      type: secret
      name: azureStorageAccountName